### ISSUE TITLE
Loading aborted due to error reloading workflow data ( This may be due to the following script: /extensions/comfyui-videohelpersuite/js/VHS.core.js)

### ISSUE THREAD

**Issue by mechonias** [Kosinkadink/ComfyUI-VideoHelperSuite#390]
Hello,

I'm sorry  yesterday everything was working, today when launching my video workflow I had an error returned and it causes problem in the UI, even if I fix the missing connections and all the workflow is kind of "unsavable" and the error restarts every time. I thin there was a ComfyUi update on my computer, is there a way I can fix this without having to redownload?

```
Loading aborted due to error reloading workflow data

TypeError: Cannot destructure property 'remote' of 'inputData[1]' as it is undefined.
TypeError: Cannot destructure property 'remote' of 'inputData[1]' as it is undefined.

    at Object.widgetConstructor [as COMBO] (http://127.0.0.1:8000/assets/index--HbqWJVC.js:161694:13)
    at ComboWidget.<anonymous> (http://127.0.0.1:8000/extensions/comfyui-videohelpersuite/js/VHS.core.js:1087:38)
    at object.<computed> [as callback] (http://127.0.0.1:8000/extensions/comfyui-videohelpersuite/js/VHS.core.js:16:29)
    at ComfyNode.<anonymous> (http://127.0.0.1:8000/extensions/comfyui-videohelpersuite/js/VHS.core.js:101:37)
    at object.<computed> (http://127.0.0.1:8000/extensions/comfyui-videohelpersuite/js/VHS.core.js:16:29)
    at ComfyNode.onConfigure (http://127.0.0.1:8000/assets/index--HbqWJVC.js:193614:18)
    at ComfyNode.configure (http://127.0.0.1:8000/assets/index--HbqWJVC.js:57338:23)
    at ComfyNode.configure (http://127.0.0.1:8000/assets/index--HbqWJVC.js:201627:15)
    at LGraph2.configure (http://127.0.0.1:8000/assets/index--HbqWJVC.js:66733:17)
    at LGraph$1.configure (http://127.0.0.1:8000/assets/index--HbqWJVC.js:209072:26)

This may be due to the following script:
/extensions/comfyui-videohelpersuite/js/VHS.core.js

```
![Image](https://github.com/user-attachments/assets/6eadd4a0-f96e-4a40-9f68-a72e4768c53a)

Any idea how  I can be able to reuse and save the workflow again? 
Sorry

**Comment by pxl-pshr** [comment]
same issue

**Comment by AustinMroz** [comment]
Duplicate of #388

**Comment by Hellrazer001** [comment]
Thank you pxt-pshr, this fixed it for me, I am not an expert on Comfyui, and wasted the last two days trying to figure it out and also lost all my Workflows. found your post and fixed in 20 seconds.

**Comment by ManOrMonster** [comment]
This is resolved after the latest ComfyUI Desktop release: https://github.com/Comfy-Org/desktop/releases/tag/v0.4.20

**Comment by RichardGoldbergSchool** [comment]
Another fix: delete all your pycache folders in your comfy folder.

**Comment by EmAySee** [comment]
not resolved... getting after updating again:

Loading aborted due to error reloading workflow data
TypeError: Cannot set property displayValue of #<NumberWidget> which has only a getter

**Comment by pxl-pshr** [comment]
same

''
# ComfyUI Error Report
## Error Details
- **Node ID:** N/A
- **Node Type:** N/A
- **Exception Type:** Loading aborted due to error reloading workflow data
- **Exception Message:** TypeError: Cannot set property displayValue of #<NumberWidget> which has only a getter
## Stack Trace
```
TypeError: Cannot set property displayValue of #<NumberWidget> which has only a getter
    at Object.assign (<anonymous>)
    at makeAnnotated (http://127.0.0.1:8188/extensions/comfyui-videohelpersuite/js/VHS.core.js:1623:12)
    at ComfyNode.<anonymous> (http://127.0.0.1:8188/extensions/comfyui-videohelpersuite/js/VHS.core.js:1819:46)
    at object.<computed> (http://127.0.0.1:8188/extensions/comfyui-videohelpersuite/js/VHS.core.js:16:29)
    at object.<computed> (http://127.0.0.1:8188/extensions/comfyui-videohelpersuite/js/VHS.core.js:15:37)
    at object.<computed> (http://127.0.0.1:8188/extensions/comfyui-videohelpersuite/js/VHS.core.js:15:37)
    at object.<computed> (http://127.0.0.1:8188/extensions/comfyui-videohelpersuite/js/VHS.core.js:15:37)
    at object.<computed> [as onNodeCreated] (http://127.0.0.1:8188/extensions/comfyui-videohelpersuite/js/VHS.core.js:15:37)
    at LiteGraphGlobal.createNode (http://127.0.0.1:8188/assets/index-CI3JuXPC.js:126309:26)
    at LGraph.configure (http://127.0.0.1:8188/assets/index-CI3JuXPC.js:125864:31)

''
