### ISSUE TITLE
ComfyUI Crashes Entirely When Video File Referenced by Node Does Not Exist

### ISSUE THREAD

**Issue by quou2006** [Kosinkadink/ComfyUI-VideoHelperSuite#555]
**Description:**
I'm experiencing a critical issue where ComfyUI completely crashes (backend process exits) when loading a workflow that contains a Load Video or Video Combine node pointing to a video file that has been deleted or does not exist.

**Steps to Reproduce:**

1. Create a workflow with a Load Video node or Video Combine node. Load or save a video file (e.g., a.mp4).
2. Save and close the workflow file.
3. Manually delete the video file a.mp4 from the filesystem.
4. Reopen the workflow file in ComfyUI.

**Expected Result:**
The UI should display an error message indicating the file cannot be found, but ComfyUI should remain running.

**Actual Result:**
ComfyUI backend process crashes immediately and exits completely. The browser frontend shows connection errors (ERR_CONNECTION_REFUSED) because the server is no longer running.

**Root Cause:**
The issue occurs in the /vhs/queryvideo API endpoint. When av.open() is called on a non-existent file path, it throws a FileNotFoundError exception. This exception is caught by a generic except Exception: pass block, which silently ignores it. However, the code continues execution with incomplete data, eventually leading to an unhandled exception that crashes the entire server process.

**Environment:**
** Platform: Windows
** Python version: 3.12.9 | packaged by conda-forge | (main, Mar  4 2025, 22:37:18) [MSC v.1943 64 bit (AMD64)]
Total VRAM 16384 MB, total RAM 32599 MB
pytorch version: 2.7.1+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
Using pytorch attention
Python version: 3.12.9 | packaged by conda-forge | (main, Mar  4 2025, 22:37:18) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.3.59
ComfyUI frontend version: 1.26.11

**Comment by AustinMroz** [comment]
Thanks for the report. I've run into another regressions I'm tracking down, but should have a fix released later tonight.

**Comment by quou2006** [comment]
**Subject:** Follow-up: Issue Not Fully Resolved - Additional Fix Required

Thank you for the quick fix in version 1.7.7. I've pulled the update, but after testing, the crash still occurs under a specific condition.

### **Root Cause of the Persistent Issue**

The current fix correctly adds a file existence check in the `resolve_path` function for local files. However, the `resolve_path` function has **multiple return paths**.

The problematic path is when `is_url(filename)` is `True`:

```python
if is_url(filename):
    file = await asyncio.to_thread(try_download_video, filename) or file
    filname, output_dir = os.path.split(file)
    return file, filename, output_dir  # ← Bypasses the new os.path.exists check!
```

When this branch is taken, the function returns a tuple directly, completely bypassing the new `os.path.exists(file)` check you added later in the function. The `query_video` function then receives this tuple, unpacks it, and proceeds to call `av.open(filepath)` on a non-existent file, causing the original crash.

### **Proposed Solution**

A more robust solution is to add a **final, universal file existence check** in the `query_video` function itself, after the path has been resolved. This ensures all code paths are validated, regardless of how the file path was obtained.

**File to modify:** `videohelpersuite/server.py`

**In the `query_video` function, after unpacking the path result:**

```python
async def query_video(request):
    try:
        query = request.rel_url.query
        path_result = await resolve_path(query)
        if isinstance(path_result, web.Response):
            return path_result
        
        filepath, filename, output_dir = path_result
        
        # === ADD THIS UNIVERSAL FILE EXISTENCE CHECK ===
        # Final safeguard to prevent av.open() call on non-existent files
        if not os.path.exists(filepath):
            return web.json_response({
                "error": f"File not found: {filepath}",
                "filename": filename
            }, status=404)
        # ==============================================
        
        if filepath.endswith(".webp"):
            return web.json_response({})
        # ... rest of the function ...
```

### **Why This is a Better Fix**

1.  **Comprehensive Coverage:** It acts as a final safety net, catching missing files from *any* return path of `resolve_path` (local files, URLs, etc.).
2.  **Better Error Reporting:** It returns a clear, informative JSON error message to the client instead of a generic `204` status, improving debugging.
3.  **Prevents the Crash at the Source:** It stops execution *before* the call to `av.open()`, which is the source of the unhandled exception that crashes the server.

This additional check, combined with your existing fix, will completely resolve the stability issue.

Thank you for your work on this plugin

**Comment by essence25** [comment]
Shouldn't this read "filename" and not "filname" ???


```
if is_url(filename):
    file = await asyncio.to_thread(try_download_video, filename) or file
--> filname, output_dir = os.path.split(file)
    return file, filename, output_dir  # ← Bypasses the new os.path.exists check!
```
